#!/bin/bash
set -euo pipefail

# always run from repo root
cd $(dirname $0)/..

rm -fr dist
mkdir -p dist

for dir in $(find ./packages -type d -not -path "*node_modules*" -name "dist"); do
  if [ -d "$dir" ]; then
    echo "collecting from ${dir}"
    rsync -aL ${dir}/ dist/
  fi
done

find dist/